export const GET_PRODUCTS_VALIDATION = 'GET_PRODUCTS_VALIDATION'
export const GET_PAYMENTS_VALIDATION = 'GET_PAYMENTS_VALIDATION'
export const GET_BILL = 'GET_BILL'
export const GET_ORDER_VALIDATION = 'GET_ORDER_VALIDATION'
export const GET_VALIDATION_FAILED = 'GET_VALIDATION_FAILED'
export const GET_VALIDATION_LOADING = 'GET_VALIDATION_LOADING'
export const GET_HOTEL = 'GET_HOTEL'

export const GET_VALIDATION_SUCCESS = "GET_VALIDATION_SUCCESS"
export const GET_ID_ESTABLISHEMENTS = "GET_ID_ESTABLISHEMENTS"
export const GET_ALL = "GET_ALL"
export const CLEAR_MESSAGE_ORDER = "CLEAR_MESSAGE_ORDER"

