export const GET_ADRESSES = 'GET_ADRESSES'
export const GET_ADRESSES_FAILED = 'GET_ADRESSES_FAILED'
export const GET_ADRESSES_LOADING = 'GET_ADRESSES_LOADING'
export const GET_DESACTIVATE_INFO = 'GET_DESACTIVATE_INFO'



