export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const LOADING = 'LOADING'
export const DELETE_MESSAGES_REGISTER = "DELETE_MESSAGES_REGISTER"


