export const GET_ESTABLISHEMENTS = 'GET_ESTABLISHEMENTS'
export const GET_PARAMS = 'GET_PARAMS'
export const GET_ESTABLISHEMENTS_LOADING = 'GET_ESTABLISHEMENTS_LOADING'
export const GET_ESTABLISHEMENTS_FAILED = 'GET_ESTABLISHEMENTS_FAILED'
export const GET_IDS = 'GET_IDS'
export const SET_FAVORIS_ESTA = 'SET_FAVORIS_ESTA'



